### ISSUE TITLE
SSM Parameter Caching

### ISSUE THREAD

**Issue by SimonEismann** [simalexan/api-lambda-stripe-charge#16]
charge.js, capture.js, and refund.js call 

`ssm.getParameter({ Name: STRIPE_SECRET_KEY_NAME, WithDecryption: true })`

for every request. Caching this result would significantly decrease the number of requests to the SSM Parameter Store. This would avoid having to deal with the SSM Parameter Throughput Configuration/Limit (https://docs.aws.amazon.com/systems-manager/latest/userguide/parameter-store-throughput.html).

If there is any interested in this, I could prepare an according pull request.

**Comment by SimonEismann** [comment]
closed as the project seems to be no longer maintained

**Comment by simalexan** [comment]
@SimonEismann Apologies, I'm a bit overwhelmed, feel free to create a PR for this if you prefer. I'll review it

**Comment by SimonEismann** [comment]
sorry, was just cleaning up my open issues and didn't realize how passive-aggressive that sounded :sweat_smile:

I've prepared a pull request, I'm not particularly familiar with Node so let me know if I messed up anything
