### ISSUE TITLE
Feature Request: Allow custom parameter name for Stripe Private Key

### ISSUE THREAD

**Issue by heitorlessa** [simalexan/api-lambda-stripe-charge#6]
Hey Alex,

 Would it be possible to add a SAR App Parameter to specify a Parameter Store name to retrieve Stripe key?
 
 Within our Payment stack, we include  `/lambda-stripe-charge/stripe-secret-key` as a CloudFormation Resource. As the Parameter name has to be unique within an AWS Account, this impacts feature branch deployments.

 Allowing a custom parameter name we could use `/service/payment/stripe-secret-key/${STAGE}` --  If you think this is a good idea I'm happy to make a PR too :)

Thanks a lot

**Comment by simalexan** [comment]
Hey Heitor, while finalizing another PR for the X-Ray Instrumentation, I've realized this issue remained. Is there anything else remaining with this issue?

**Comment by simalexan** [comment]
I've closed this, in case you need something more, please do ask.
